# Generated by Django 2.0.6 on 2020-04-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('salt', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 't_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=50, null=True)),
                ('voice_url', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_chapter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(blank=True, max_length=50, null=True)),
                ('homework_data', models.DateTimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_counter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TGhosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=20, null=True)),
                ('albumt_img', models.ImageField(blank=True, default=None, max_length=50, null=True, upload_to='pic')),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('broadcast', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('issue_data', models.DateTimeField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_ghosa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='THomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sort', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_homework',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, default=None, null=True, upload_to='pic')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('upload_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 't_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('religious_name', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('head_img', models.ImageField(blank=True, default=None, max_length=50, null=True, upload_to='pic')),
                ('salt', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('register_data', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='thomework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admins.TUser'),
        ),
        migrations.AddField(
            model_name='tcounter',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admins.THomework'),
        ),
        migrations.AddField(
            model_name='tchapter',
            name='buddhist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admins.TGhosa'),
        ),
    ]
