# Generated by Django 2.0.6 on 2020-04-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20200414_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tadmin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tchapter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tcounter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tghosa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='thomework',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='timage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tuser',
            options={'managed': False},
        ),
    ]
