# Generated by Django 2.0.6 on 2020-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('content', models.TextField()),
                ('head_pic', models.ImageField(blank=True, default=None, max_length=50, null=True, upload_to='pic')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
