# Generated by Django 2.0.6 on 2020-04-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='head_pic',
        ),
    ]
